<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>haochat-tools</artifactId>
        <groupId>com.ahao.haochat</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>haochat-transaction</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.ahao.haochat</groupId>
            <artifactId>haochat-common-starter</artifactId>
        </dependency>
    </dependencies>
</project>