#todo 记得把这些配置信息补充了
##################mysql配置##################
haochat.mysql.ip=127.0.0.1
haochat.mysql.port=3306
haochat.mysql.db=haochat
haochat.mysql.username=root
haochat.mysql.password=YOUR_MYSQL_PASSWORD
##################redis配置##################
haochat.redis.host=127.0.0.1
haochat.redis.port=6379
haochat.redis.password=YOUR_REDIS_PASSWORD
##################jwt##################
haochat.jwt.secret=YOUR_JWT_SECRET
##################微信公众号信息##################
haochat.wx.callback=http://127.0.0.1:8080
haochat.wx.appId=appid
haochat.wx.secret=YOUR_WECHAT_SECRET
# 接口配置里的Token值
haochat.wx.token=sdfsf
# 接口配置里的EncodingAESKey值
haochat.wx.aesKey=sha1
##################OSS配置##################
oss.enabled=true
oss.type=minio
oss.endpoint=http://ahao.space
oss.access-key=YOUR_OSS_ACCESS_KEY
oss.secret-key=YOUR_OSS_SECRET_KEY
oss.bucketName=default
##################rocketmq##################
rocketmq.name-server=127.0.0.1:9876
rocketmq.access-key=YOUR_ROCKETMQ_ACCESS_KEY
rocketmq.secret-key=YOUR_ROCKETMQ_SECRET_KEY
##################gpt配置##################
haochat.chatgpt.use=false
haochat.chatgpt.uid=10001
haochat.chatgpt.key=YOUR_OPENAI_KEY
haochat.chatgpt.proxyUrl=https://123.cc
haochat.chatglm2.use=false
haochat.chatglm2.url=http://v32134.cc
haochat.chatglm2.uid=10002
haochat.chatglm2.context=3
